# Generated by Django 5.0.3 on 2024-03-18 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'db_table': 'raza',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tamaño', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Tamaños',
                'db_table': 'tamaño',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo cita',
                'verbose_name_plural': 'Tipo citas',
                'db_table': 'tipo_citas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('peso', models.CharField(default='0', max_length=30)),
                ('edad', models.IntegerField(default=0, verbose_name='Edad')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_citas.raza')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_citas.tamano')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascota',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgendarCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('Hora', models.TimeField(verbose_name='Hora de la cita')),
                ('Telefono', models.CharField(max_length=15, verbose_name='Número de contacto')),
                ('descripcion', models.TextField(default='', max_length=200, verbose_name='Descripcion')),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendarcitas_name', to='gestion_citas.mascota')),
                ('nombre_tipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_citas.tipo_citas')),
            ],
            options={
                'verbose_name': 'Agendar cita',
                'verbose_name_plural': 'Agendar citas',
                'db_table': 'AgendarCita',
                'ordering': ['id'],
            },
        ),
    ]
