# Generated by Django 4.2.4 on 2023-09-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('seleccionar', 'seleccionar'), ('baño', 'baño'), ('peluqueada', 'peluqueada'), ('baño y peluqueada', 'baño y peluqueada')], max_length=100, verbose_name='Tipo_cita')),
                ('size', models.CharField(choices=[('seleccionar', 'seleccionar'), ('grande', 'grande'), ('mediano', 'mediano'), ('pequeño', 'Pequeño')], max_length=100, verbose_name='Tamaño_mascota')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre_mascota')),
                ('day', models.DateField(verbose_name='Fecha de la Cita')),
                ('hour', models.TimeField(verbose_name='Hora de la Cita')),
                ('phone', models.CharField(max_length=15, verbose_name='Numero_contacto')),
            ],
        ),
    ]
