# Generated by Django 4.2.4 on 2023-09-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Baño', 'Baño'), ('Peluqueada', 'Peluqueada'), ('Baño y Peluqueada', 'Baño y Peluqueada')], max_length=100, verbose_name='Tipo cita')),
                ('size', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Grande', 'Grande'), ('mediano', 'mediano'), ('pequeño', 'pequeño')], max_length=100, verbose_name='Tamaño mascota')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre mascosta')),
                ('day', models.DateField(verbose_name='Fecha de la cita')),
                ('hour', models.TimeField(verbose_name='Hora de la cita')),
                ('phone', models.CharField(max_length=15, verbose_name='Numero de contacto')),
            ],
        ),
    ]
