# Generated by Django 4.2.4 on 2023-09-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0002_mascota_alter_agendar_cita_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendarCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Baño', 'Baño'), ('Peluqueada', 'Peluqueada'), ('Baño y Peluqueada', 'Baño y Peluqueada')], max_length=100, verbose_name='Tipo cita')),
                ('size', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeño', 'Pequeño')], max_length=100, verbose_name='Tamaño mascota')),
                ('day', models.DateField(verbose_name='Fecha de la cita')),
                ('hour', models.TimeField(verbose_name='Hora de la cita')),
                ('phone', models.CharField(max_length=15, verbose_name='Número de contacto')),
            ],
            options={
                'verbose_name': 'Agendar cita',
                'verbose_name_plural': 'Agendar citas',
                'db_table': 'Agendar_cita',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['id'], 'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='Nombre_mascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(default='Nombre Predeterminado', max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name='mascota',
            table='mascota',
        ),
        migrations.DeleteModel(
            name='Agendar_cita',
        ),
        migrations.AddField(
            model_name='agendarcita',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_citas.mascota'),
        ),
    ]
