# Generated by Django 4.2.4 on 2023-09-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0003_agendarcita_alter_mascota_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendarcita',
            table='AgendarCita',
        ),
    ]
