# Generated by Django 4.2.4 on 2023-09-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0005_tamaño_alter_agendarcita_type_alter_mascota_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeño', 'Pequeño')], default='Seleccionar', max_length=100, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='agendarcita',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendarcitas_name', to='gestion_citas.mascota'),
        ),
        migrations.AlterField(
            model_name='agendarcita',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendarcitas_size', to='gestion_citas.mascota'),
        ),
        migrations.DeleteModel(
            name='Tamaño',
        ),
    ]
