# Generated by Django 4.2.4 on 2023-09-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0006_mascota_tamaño_alter_agendarcita_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='tamaño',
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeño', 'Pequeño')], default='Seleccionar', max_length=100, verbose_name='Tamaño')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_citas.mascota')),
            ],
            options={
                'verbose_name': 'tamaño',
                'verbose_name_plural': 'tamaños',
                'db_table': 'tamaño',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='agendarcita',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendarcitas_size', to='gestion_citas.tamaño'),
        ),
    ]
