# Generated by Django 4.2.4 on 2023-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0007_remove_mascota_tamaño_tamaño_alter_agendarcita_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendarcita',
            old_name='day',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='agendarcita',
            old_name='hour',
            new_name='Hora',
        ),
        migrations.RenameField(
            model_name='agendarcita',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='agendarcita',
            old_name='phone',
            new_name='Telefono',
        ),
        migrations.RenameField(
            model_name='agendarcita',
            old_name='type',
            new_name='Tipo_cita',
        ),
        migrations.RenameField(
            model_name='tamaño',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='agendarcita',
            name='size',
        ),
        migrations.AddField(
            model_name='agendarcita',
            name='descripcion',
            field=models.TextField(default='Sin descripción', max_length=200, verbose_name='Descripcion de la mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=0, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='peso',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default='Desconocida', max_length=30),
        ),
    ]
