# Generated by Django 4.2.4 on 2023-09-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0008_rename_day_agendarcita_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarcita',
            name='descripcion',
            field=models.TextField(default='', max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default='', max_length=30),
        ),
    ]
