# Generated by Django 5.0.2 on 2024-03-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_categoria', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Categoria producto',
                'verbose_name_plural': 'Categorias producto',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_compra', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Compra producto',
                'verbose_name_plural': 'Compras   producto',
                'db_table': 'compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_producto', models.CharField(max_length=30)),
                ('Precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock_producto', models.IntegerField()),
                ('Imagen_producto', models.CharField(max_length=100)),
                ('Descripcion_producto', models.CharField(max_length=50)),
                ('Id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
    ]
