# Generated by Django 5.0.2 on 2024-03-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_id_marca_delete_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Stock_producto',
            field=models.IntegerField(),
        ),
    ]
