# Generated by Django 4.2.4 on 2023-09-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=100, verbose_name='TIPO PQRS')),
                ('Date', models.DateField(verbose_name='Fecha')),
                ('Name', models.CharField(max_length=100, verbose_name='Nombre Usuario')),
                ('Sender', models.TextField(max_length=500, verbose_name='Descripcion')),
            ],
        ),
    ]
