# Generated by Django 4.2.4 on 2023-09-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_pqrs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
