# Generated by Django 4.2.4 on 2023-09-10 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0002_auto_20230909_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='Estado_pqrs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PQRS.estado'),
        ),
    ]
