# Generated by Django 4.2.4 on 2023-09-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compras',
        ),
    ]
